version: '3'

services:
  strapi:
    build: .
    container_name: systematic-strapi
    restart: unless-stopped
    ports:
      - '1696:1696'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1696
      - APP_KEYS=toBeModified1,toBeModified2
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - TRANSFER_TOKEN_SALT=tobemodified
      - JWT_SECRET=tobemodified
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./database:/app/database
    networks:
      - strapi-network

networks:
  strapi-network:
    driver: bridge 